"""Generate synthetic SOC/OCV fixture files covering edge cases the
data_formatter pipeline must handle: different delimiters, decimal styles,
headers/footers, swapped columns, percentage SOC, non-monotonic data,
quoted CSV fields, and invalid files.

Run once (or whenever fixtures need regenerating):
    python tests/make_fixtures.py
"""
import os
import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
FDIR = os.path.join(HERE, "fixtures")
os.makedirs(FDIR, exist_ok=True)

soc = np.linspace(0, 1, 30)
ocv = 2.5 + 1.1 * soc + 0.05 * np.sin(soc * 3)  # ascending, cathode-like

# 1. comma-delimited with header
with open(os.path.join(FDIR, "comma_header.csv"), "w") as f:
    f.write("SOC,OCV\n")
    for x, y in zip(soc, ocv):
        f.write(f"{x},{y}\n")

# 2. semicolon-delimited with comma decimals + header
with open(os.path.join(FDIR, "semicolon_commadecimal.csv"), "w") as f:
    f.write("SOC;OCV\n")
    for x, y in zip(soc, ocv):
        f.write(f"{str(x).replace('.', ',')};{str(y).replace('.', ',')}\n")

# 3. xlsx with header + footer
df = pd.DataFrame({"SOC": soc, "OCV": ocv})
with pd.ExcelWriter(os.path.join(FDIR, "with_header_footer.xlsx")) as writer:
    df.to_excel(writer, index=False, header=True, startrow=0)
import openpyxl
wb = openpyxl.load_workbook(os.path.join(FDIR, "with_header_footer.xlsx"))
ws = wb.active
ws.append(["Notes:", "exported from BT-Lab v3.2"])  # footer row
wb.save(os.path.join(FDIR, "with_header_footer.xlsx"))

# 4. swapped columns (OCV first, SOC second), whitespace-delimited, no header
with open(os.path.join(FDIR, "swapped_columns.txt"), "w") as f:
    for x, y in zip(soc, ocv):
        f.write(f"{y} {x}\n")

# 5. SOC given as 0-100 percentage, tab-delimited
with open(os.path.join(FDIR, "percentage_soc.txt"), "w") as f:
    for x, y in zip(soc, ocv):
        f.write(f"{x * 100}\t{y}\n")

# 6. non-monotonic dip: soc mostly increasing but with a real reversal
soc_bad = soc.copy()
soc_bad[15:20] = np.linspace(0.55, 0.3, 5)
with open(os.path.join(FDIR, "non_monotonic.txt"), "w") as f:
    for x, y in zip(soc_bad, ocv):
        f.write(f"{x} {y}\n")

# 7. quoted CSV fields
with open(os.path.join(FDIR, "quoted.csv"), "w") as f:
    f.write('"SOC","OCV"\n')
    for x, y in zip(soc, ocv):
        f.write(f'"{x}","{y}"\n')

# 8. header + footer, whitespace delimited
with open(os.path.join(FDIR, "header_footer_whitespace.txt"), "w") as f:
    f.write("State of Charge and Open Circuit Voltage export\n")
    for x, y in zip(soc, ocv):
        f.write(f"{x} {y}\n")
    f.write("End of file - generated by ExportTool 2.1\n")

# 9. invalid: non-numeric row in the middle
with open(os.path.join(FDIR, "invalid_interior.txt"), "w") as f:
    for i, (x, y) in enumerate(zip(soc, ocv)):
        f.write(f"{x} {y}\n")
        if i == 10:
            f.write("ERROR: sensor disconnected\n")

# 10. too few rows
with open(os.path.join(FDIR, "too_few_rows.txt"), "w") as f:
    f.write("0.0 2.5\n0.5 3.0\n")

# 11. more than two columns, led by a bare row index — the shape most lab
# exports actually have, and the case the column picker exists for. The
# index is monotonic like a real SOC column, so a heuristic that only
# looks for "rises steadily" can be fooled into choosing it.
with open(os.path.join(FDIR, "indexed_three_column.txt"), "w") as f:
    f.write("Index\tSOC\tOCV\n")
    for i, (x, y) in enumerate(zip(soc, ocv), start=1):
        f.write(f"{i}\t{x}\t{y}\n")

# 12. the same, as a wider csv with columns either side of the useful two
with open(os.path.join(FDIR, "indexed_five_column.csv"), "w") as f:
    f.write("Index,Time_s,SOC,OCV,Current_A\n")
    for i, (x, y) in enumerate(zip(soc, ocv), start=1):
        f.write(f"{i},{i * 60},{x},{y},{0.05:.3f}\n")

print("Fixtures created in", FDIR)
print(os.listdir(FDIR))
